### ISSUE TITLE
Portfolio ページ追加

### ISSUE THREAD

**Issue by sora-ichigo** [igsr5/igsr5-front#16]
## 作るページ
- 実績一覧
  ![Screen Shot 2022-02-06 at 15 56 07](https://user-images.githubusercontent.com/66525257/152670744-59f6a69f-3d89-48d2-ba14-edf916980d0e.png)
- 実績詳細
  ![Screen Shot 2022-02-06 at 15 56 37](https://user-images.githubusercontent.com/66525257/152670759-8971f131-ca61-42a1-b419-7b2f9e72ec98.png)
 
## 備考
- 絞り込み検索を実装する
- 実績のデータ構造を考える必要がある
- 実装詳細はモーダルでいい感じに出す

**Comment by sora-ichigo** [comment]
> 実績のデータ構造を考える必要がある

必要そうなデータ

⭐  がついているのは一覧ページでも使うもの

- ⭐  ID - number
- ⭐  タイトル - string
- ⭐  カテゴリー - categoryType (自実装)
- ⭐  サムネイル画像 URL - string
- 作成日時 - timestamp （ソートしたいかも？）
- 開発スタイル - 個人 or チーム を表現できればOK (number かな)
- 詳細 - string
- タグ - string[]
- 画像 URL - string
- 外部リンク - string

**Comment by sora-ichigo** [comment]
## レスポンシブ対応
基本的に実績一覧はカラム数が変動するだけ。

### lg (1024px~)
3 カラム

### sm~ (640px~)
2 カラム

## ~sm (~640px)
1 カラム

**Comment by sora-ichigo** [comment]
勢い余って close してしまった。まだ詳細ページが残っている

**Comment by igsr5** [comment]
📝  実装の簡単化のためとりあえず詳細ページでは URL は変わらないままにする

**Comment by sora-ichigo** [comment]
モーダル実装には https://github.com/reactjs/react-modal を使う

**Comment by sora-ichigo** [comment]
![Screen Shot 2022-02-06 at 21 00 25](https://user-images.githubusercontent.com/66525257/152679796-2f8e48ec-955f-458b-9fe1-9f71d8d2b7ed.png)

画像が 2枚以上表示されているが、とりあえず 1枚　のみで対応する

**Comment by sora-ichigo** [comment]
（サムネ画像と中身の画像違うのか、、）

**Comment by sora-ichigo** [comment]
<img width="715" alt="Screen Shot 2022-02-08 at 2 19 49" src="https://user-images.githubusercontent.com/66525257/152838958-fc13120f-0132-4a26-8a20-6b1d8e74eabd.png">

関連タグのコンポーネント作る
